### PR TITLE
General improvements for maintainability

### PR DESCRIPTION
**Pull request by pgmitche**
## Description

This PR includes the following changes:

- Extensive documentation improvements
- Extensive identifier renaming for legibility and maintainability
- Flow control updates for improving logic clarity
- Uplifted to recent go version

## Acceptance Criteria

Required: 
 - [x] Unit tests
 
Prompts:
 - [x] GoDoc
 - [x] Readme

### CODE REVIEW

**Comment by pgmitche** [comment]
@tglennan are you folks still using this? Making some documentation, naming and other general improvements here. Would be good to get some testing internally with real copybooks if possible when this get's closer to merging

**Comment by pgmitche** [comment]
Sending it 🚀

**Comment by tglennan** [comment]
> @tglennan are you folks still using this? Making some documentation, naming and other general improvements here. Would be good to get some testing internally with real copybooks if possible when this get's closer to merging to ensure I don't break anything for you.

Apologies, totally missed this 🙏 

Looks like it was forked and is being maintained internally now

**Comment by pgmitche** [comment]
> Apologies, totally missed this 🙏
> 
> Looks like it was forked and is being maintained internally now

All good, don't think I introduced any regressions here.

Shame about that, hopefully they can pull in these improvements.

**Pull request merged**
